### KPIs: utilization %, avg fare/km, avg idle time, outlier count

In [1]:
from clickhouse_driver import Client

client = Client(
        host='localhost',
        port=int(9000),
        user='click',
        password='click',
        database='pl',
    )

In [6]:
query = '''
SELECT driver_id
, date_trunc('day', pickup_datetime) as day
, sum(dateDiff('second', pickup_datetime, dropoff_datetime))/3600 as trip_hours
FROM staging.nyc_tlc_tripdata_local
group by driver_id, day
'''

df = client.query_dataframe(query)
df

        driver_id                       day  trip_hours
0             465 2025-06-18 00:00:00+00:00   44.639722
1               7 2025-08-25 00:00:00+00:00   25.212222
2             836 2025-08-16 00:00:00+00:00   54.153333
3             508 2025-04-09 00:00:00+00:00   39.261667
4             383 2025-06-04 00:00:00+00:00   51.174167
...           ...                       ...         ...
214026        892 2025-09-25 00:00:00+00:00   49.360556
214027         53 2025-05-05 00:00:00+00:00   40.842500
214028        175 2025-08-03 00:00:00+00:00   31.295556
214029        157 2025-04-12 00:00:00+00:00   36.890556
214030        252 2025-05-02 00:00:00+00:00   38.708611

[214031 rows x 3 columns]

In [7]:
df.describe()

           driver_id     trip_hours
count  214031.000000  214031.000000
mean      500.490863      40.538100
std       288.675343       9.816096
min         1.000000       0.001111
25%       250.000000      33.883889
50%       500.000000      39.515556
75%       750.000000      45.945278
max      1000.000000     280.115556

In [ ]:
import plotly.express as px

# Время поездки в часах
df["trip_time"] = (df["dropoff_datetime"] - df["pickup_datetime"]).dt.total_seconds() / 3600


# Время смены в часах (24 часа)
df["shift_time"] = 24

# Расчет коэффициента использования
shift["utilization_rate"] = shift["total_trip_time"] / shift["shift_time"]

shift.head()

In [ ]:


# Визуализация
px.bar(
    shift,
    x="fleet",
    y="utilization_rate",
    text="utilization_rate",
    title="Fleet Utilization Rate"
).show()